// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using URL_Shortener.Data;

#nullable disable

namespace URL_Shortener.data.migrations
{
    [DbContext(typeof(UrlShortenerDBContext))]
    [Migration("20250523175115_AddedConvertedAtField")]
    partial class AddedConvertedAtField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("URL_Shortener.Models.URLLinks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ConvertedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortenedUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortenedUrlPrefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimesVisited")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VisitorsIpAddress")
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("Id");

                    b.ToTable("UrlLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
